import { Router } from 'express';
import users from '../../user/user.routes';
import auth from '../../auth/auth.routes';
import post from '../../post/post.routes';
import follow from '../../follow/follow.routes';
import comment from '../../comment/comment.routes';
import like from '../../like/like.routes';
import bookmark from '../../bookmark/bookmark.routes';
import search from '../../search/search.routes';
import chat from '../../chat/chat.routes';
const router = Router();

router.use('/users', users);
router.use('/auth', auth);
router.use('/post', post);
router.use('/follow', follow);
router.use('/comment', comment);
router.use('/like', like);
router.use('/Bookmark', bookmark);
router.use('/search', search);
router.use('/chat', chat);
export default router;
